export const SEARCH_RESULTS_FETCH = 'SEARCH_RESULTS_FETCH';
export const SEARCH_RESULTS_RECEIVE = 'SEARCH_RESULTS_RECEIVE';
export const SEARCH_RESULTS_CLEAR = 'SEARCH_RESULTS_CLEAR';

export const WAYPOINT_ADD = 'WAYPOINT_ADD';
export const WAYPOINT_REMOVE = 'WAYPOINT_REMOVE';
export const WAYPOINT_MOVE_UP = 'WAYPOINT_MOVE_UP';
export const WAYPOINT_MOVE_DOWN = 'WAYPOINT_MOVE_DOWN';